language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
  - cp CNAME docs/.vuepress/dist/CNAME
  - ls docs/.vuepress/dist/
  - cat docs/.vuepress/dist/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target_branch: master
  on:
    branch: build